default["openstack"]["release"] = "folsom"
default["openstack"]["folsom"]["ubuntu"]["repo"] = "http://ubuntu-cloud.archive.canonical.com/ubuntu"
default["openstack"]["folsom"]["ubuntu"]["dist"] = "precise-updates/folsom"
default["openstack"]["folsom"]["ubuntu"]["components"] = "main"
default["openstack"]["folsom"]["ubuntu"]["key"] = "0x81DCD8423B6F61A6"
default["openstack"]["folsom"]["ubuntu"]["keyserver"] = "keyserver.ubuntu.com"
